version: "3.5"

services:
  # my-redis-stack:
  #   container_name: my-redis-stack
  #   image: redis/redis-stack:latest
  #   ports:
  #     - 6379:6379
  #     - 8001:8001
  #   restart: no
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  local-bullboard:
    container_name: local-bullboard
    image: bull-board
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USE_TLS: false
      BULL_PREFIX: bull
      BULL_QUEUES: industry
    ports:
      - 8002:3000
    depends_on:
      - redis

  bullboard:
    container_name: prod-bullboard
    image: bull-board
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      REDIS_PORT: 6379
      REDIS_USE_TLS: true
      BULL_PREFIX: bull
      BULL_QUEUES: industry
    ports:
      - 8003:3000

volumes:
  redis-data:
