services:
  bullboard:
    container_name: bullboard
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
#      BULL_VERSION: BULL
    healthcheck:
      test: [ 'CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:3000/healthcheck || exit 1']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "3000:3000"

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
