// const LOCAL_DEVELOPMENT = process.env.NODE_ENV === "development"
const LOCAL_DEVELOPMENT = false;

export const SUPABASE_SERVICE_ROLE_KEY = LOCAL_DEVELOPMENT
  ? process.env.LOCAL_SUPABASE_SERVICE_ROLE_KEY
  : process.env.SUPABASE_SERVICE_ROLE_KEY;
export const SUPABASE_ANON_KEY = LOCAL_DEVELOPMENT
  ? process.env.NEXT_PUBLIC_LOCAL_SUPABASE_ANON_KEY
  : process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
export const SUPABASE_URL = LOCAL_DEVELOPMENT
  ? process.env.NEXT_PUBLIC_LOCAL_SUPABASE_URL
  : process.env.NEXT_PUBLIC_SUPABASE_URL;
